# Generated by Django 5.0.3 on 2024-12-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(choices=[('Free', 'Free'), ('Star', 'Star')], default='Free', max_length=20),
        ),
    ]
