# Generated by Django 5.0.3 on 2024-08-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_menuitems_menu_photo_new_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staller',
            name='egit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.egit'),
        ),
    ]
