# Generated by Django 5.0.3 on 2024-11-17 12:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_staller_least_price_menuitems_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staller',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staller',
            name='locality_preferred_for',
            field=models.CharField(choices=[('family', 'Family'), ('friends', 'Friends'), ('couples', 'Couples')], default='Family', max_length=10),
        ),
        migrations.AddField(
            model_name='staller',
            name='locality_visited_with',
            field=models.CharField(choices=[('family', 'Family'), ('friends', 'Friends'), ('couples', 'Couples')], default='Family', max_length=10),
        ),
        migrations.AddField(
            model_name='staller',
            name='location_accuracy',
            field=models.PositiveIntegerField(blank=True, help_text='Enter a percentage value between 0 and 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='staller',
            name='owner_behaviour',
            field=models.CharField(choices=[('bad', 'Bad'), ('average', 'Average'), ('good', 'Good'), ('great', 'Great')], default='Good', max_length=10),
        ),
        migrations.AddField(
            model_name='staller',
            name='payr',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='staller',
            name='rush',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staller',
            name='surrounding_landmarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='menu_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/menu_pics/'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='normal_price',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='premium_price',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'staller')},
            },
        ),
    ]
